#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oxite.Modules.CMS.Repositories.SqlServer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Oxite.Database")]
	public partial class OxiteCMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertoxite_CMS_PageRoleUserRelationship(oxite_CMS_PageRoleUserRelationship instance);
    partial void Updateoxite_CMS_PageRoleUserRelationship(oxite_CMS_PageRoleUserRelationship instance);
    partial void Deleteoxite_CMS_PageRoleUserRelationship(oxite_CMS_PageRoleUserRelationship instance);
    partial void Insertoxite_CMS_Page(oxite_CMS_Page instance);
    partial void Updateoxite_CMS_Page(oxite_CMS_Page instance);
    partial void Deleteoxite_CMS_Page(oxite_CMS_Page instance);
    partial void Insertoxite_User(oxite_User instance);
    partial void Updateoxite_User(oxite_User instance);
    partial void Deleteoxite_User(oxite_User instance);
    partial void Insertoxite_CMS_ContentItem(oxite_CMS_ContentItem instance);
    partial void Updateoxite_CMS_ContentItem(oxite_CMS_ContentItem instance);
    partial void Deleteoxite_CMS_ContentItem(oxite_CMS_ContentItem instance);
    #endregion
		
		public OxiteCMSDataContext() : 
				base("Data Source=.\\SQLEXPRESS;Initial Catalog=Oxite.Database;Integrated Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public OxiteCMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OxiteCMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OxiteCMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OxiteCMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<oxite_CMS_PageRoleUserRelationship> oxite_CMS_PageRoleUserRelationships
		{
			get
			{
				return this.GetTable<oxite_CMS_PageRoleUserRelationship>();
			}
		}
		
		public System.Data.Linq.Table<oxite_CMS_Page> oxite_CMS_Pages
		{
			get
			{
				return this.GetTable<oxite_CMS_Page>();
			}
		}
		
		public System.Data.Linq.Table<oxite_User> oxite_Users
		{
			get
			{
				return this.GetTable<oxite_User>();
			}
		}
		
		public System.Data.Linq.Table<oxite_CMS_ContentItem> oxite_CMS_ContentItems
		{
			get
			{
				return this.GetTable<oxite_CMS_ContentItem>();
			}
		}
	}
	
	[Table(Name="dbo.oxite_CMS_PageRoleUserRelationship")]
	public partial class oxite_CMS_PageRoleUserRelationship : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PageID;
		
		private System.Guid _RoleID;
		
		private System.Guid _UserID;
		
		private EntityRef<oxite_CMS_Page> _oxite_CMS_Page;
		
		private EntityRef<oxite_User> _oxite_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPageIDChanging(System.Guid value);
    partial void OnPageIDChanged();
    partial void OnRoleIDChanging(System.Guid value);
    partial void OnRoleIDChanged();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    #endregion
		
		public oxite_CMS_PageRoleUserRelationship()
		{
			this._oxite_CMS_Page = default(EntityRef<oxite_CMS_Page>);
			this._oxite_User = default(EntityRef<oxite_User>);
			OnCreated();
		}
		
		[Column(Storage="_PageID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PageID
		{
			get
			{
				return this._PageID;
			}
			set
			{
				if ((this._PageID != value))
				{
					if (this._oxite_CMS_Page.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPageIDChanging(value);
					this.SendPropertyChanging();
					this._PageID = value;
					this.SendPropertyChanged("PageID");
					this.OnPageIDChanged();
				}
			}
		}
		
		[Column(Storage="_RoleID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._oxite_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Association(Name="oxite_CMS_Page_oxite_CMS_PageRoleUserRelationship", Storage="_oxite_CMS_Page", ThisKey="PageID", OtherKey="PageID", IsForeignKey=true)]
		public oxite_CMS_Page oxite_CMS_Page
		{
			get
			{
				return this._oxite_CMS_Page.Entity;
			}
			set
			{
				oxite_CMS_Page previousValue = this._oxite_CMS_Page.Entity;
				if (((previousValue != value) 
							|| (this._oxite_CMS_Page.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oxite_CMS_Page.Entity = null;
						previousValue.oxite_CMS_PageRoleUserRelationships.Remove(this);
					}
					this._oxite_CMS_Page.Entity = value;
					if ((value != null))
					{
						value.oxite_CMS_PageRoleUserRelationships.Add(this);
						this._PageID = value.PageID;
					}
					else
					{
						this._PageID = default(System.Guid);
					}
					this.SendPropertyChanged("oxite_CMS_Page");
				}
			}
		}
		
		[Association(Name="oxite_User_oxite_CMS_PageRoleUserRelationship", Storage="_oxite_User", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public oxite_User oxite_User
		{
			get
			{
				return this._oxite_User.Entity;
			}
			set
			{
				oxite_User previousValue = this._oxite_User.Entity;
				if (((previousValue != value) 
							|| (this._oxite_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oxite_User.Entity = null;
						previousValue.oxite_CMS_PageRoleUserRelationships.Remove(this);
					}
					this._oxite_User.Entity = value;
					if ((value != null))
					{
						value.oxite_CMS_PageRoleUserRelationships.Add(this);
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(System.Guid);
					}
					this.SendPropertyChanged("oxite_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.oxite_CMS_Page")]
	public partial class oxite_CMS_Page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SiteID;
		
		private System.Guid _PageID;
		
		private string _TemplateName;
		
		private string _Title;
		
		private string _Description;
		
		private string _Slug;
		
		private System.Nullable<System.DateTime> _PublishedDate;
		
		private EntitySet<oxite_CMS_PageRoleUserRelationship> _oxite_CMS_PageRoleUserRelationships;
		
		private EntitySet<oxite_CMS_ContentItem> _oxite_CMS_ContentItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteIDChanging(System.Guid value);
    partial void OnSiteIDChanged();
    partial void OnPageIDChanging(System.Guid value);
    partial void OnPageIDChanged();
    partial void OnTemplateNameChanging(string value);
    partial void OnTemplateNameChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSlugChanging(string value);
    partial void OnSlugChanged();
    partial void OnPublishedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishedDateChanged();
    #endregion
		
		public oxite_CMS_Page()
		{
			this._oxite_CMS_PageRoleUserRelationships = new EntitySet<oxite_CMS_PageRoleUserRelationship>(new Action<oxite_CMS_PageRoleUserRelationship>(this.attach_oxite_CMS_PageRoleUserRelationships), new Action<oxite_CMS_PageRoleUserRelationship>(this.detach_oxite_CMS_PageRoleUserRelationships));
			this._oxite_CMS_ContentItems = new EntitySet<oxite_CMS_ContentItem>(new Action<oxite_CMS_ContentItem>(this.attach_oxite_CMS_ContentItems), new Action<oxite_CMS_ContentItem>(this.detach_oxite_CMS_ContentItems));
			OnCreated();
		}
		
		[Column(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[Column(Storage="_PageID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PageID
		{
			get
			{
				return this._PageID;
			}
			set
			{
				if ((this._PageID != value))
				{
					this.OnPageIDChanging(value);
					this.SendPropertyChanging();
					this._PageID = value;
					this.SendPropertyChanged("PageID");
					this.OnPageIDChanged();
				}
			}
		}
		
		[Column(Storage="_TemplateName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TemplateName
		{
			get
			{
				return this._TemplateName;
			}
			set
			{
				if ((this._TemplateName != value))
				{
					this.OnTemplateNameChanging(value);
					this.SendPropertyChanging();
					this._TemplateName = value;
					this.SendPropertyChanged("TemplateName");
					this.OnTemplateNameChanged();
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_Slug", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this.OnSlugChanging(value);
					this.SendPropertyChanging();
					this._Slug = value;
					this.SendPropertyChanged("Slug");
					this.OnSlugChanged();
				}
			}
		}
		
		[Column(Storage="_PublishedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishedDate
		{
			get
			{
				return this._PublishedDate;
			}
			set
			{
				if ((this._PublishedDate != value))
				{
					this.OnPublishedDateChanging(value);
					this.SendPropertyChanging();
					this._PublishedDate = value;
					this.SendPropertyChanged("PublishedDate");
					this.OnPublishedDateChanged();
				}
			}
		}
		
		[Association(Name="oxite_CMS_Page_oxite_CMS_PageRoleUserRelationship", Storage="_oxite_CMS_PageRoleUserRelationships", ThisKey="PageID", OtherKey="PageID")]
		public EntitySet<oxite_CMS_PageRoleUserRelationship> oxite_CMS_PageRoleUserRelationships
		{
			get
			{
				return this._oxite_CMS_PageRoleUserRelationships;
			}
			set
			{
				this._oxite_CMS_PageRoleUserRelationships.Assign(value);
			}
		}
		
		[Association(Name="oxite_CMS_Page_oxite_CMS_ContentItem", Storage="_oxite_CMS_ContentItems", ThisKey="PageID", OtherKey="PageID")]
		public EntitySet<oxite_CMS_ContentItem> oxite_CMS_ContentItems
		{
			get
			{
				return this._oxite_CMS_ContentItems;
			}
			set
			{
				this._oxite_CMS_ContentItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oxite_CMS_PageRoleUserRelationships(oxite_CMS_PageRoleUserRelationship entity)
		{
			this.SendPropertyChanging();
			entity.oxite_CMS_Page = this;
		}
		
		private void detach_oxite_CMS_PageRoleUserRelationships(oxite_CMS_PageRoleUserRelationship entity)
		{
			this.SendPropertyChanging();
			entity.oxite_CMS_Page = null;
		}
		
		private void attach_oxite_CMS_ContentItems(oxite_CMS_ContentItem entity)
		{
			this.SendPropertyChanging();
			entity.oxite_CMS_Page = this;
		}
		
		private void detach_oxite_CMS_ContentItems(oxite_CMS_ContentItem entity)
		{
			this.SendPropertyChanging();
			entity.oxite_CMS_Page = null;
		}
	}
	
	[Table(Name="dbo.oxite_User")]
	public partial class oxite_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserID;
		
		private string _Username;
		
		private string _DisplayName;
		
		private string _Email;
		
		private string _HashedEmail;
		
		private System.Guid _DefaultLanguageID;
		
		private byte _Status;
		
		private EntitySet<oxite_CMS_PageRoleUserRelationship> _oxite_CMS_PageRoleUserRelationships;
		
		private EntitySet<oxite_CMS_ContentItem> _oxite_CMS_ContentItems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHashedEmailChanging(string value);
    partial void OnHashedEmailChanged();
    partial void OnDefaultLanguageIDChanging(System.Guid value);
    partial void OnDefaultLanguageIDChanged();
    partial void OnStatusChanging(byte value);
    partial void OnStatusChanged();
    #endregion
		
		public oxite_User()
		{
			this._oxite_CMS_PageRoleUserRelationships = new EntitySet<oxite_CMS_PageRoleUserRelationship>(new Action<oxite_CMS_PageRoleUserRelationship>(this.attach_oxite_CMS_PageRoleUserRelationships), new Action<oxite_CMS_PageRoleUserRelationship>(this.detach_oxite_CMS_PageRoleUserRelationships));
			this._oxite_CMS_ContentItems = new EntitySet<oxite_CMS_ContentItem>(new Action<oxite_CMS_ContentItem>(this.attach_oxite_CMS_ContentItems), new Action<oxite_CMS_ContentItem>(this.detach_oxite_CMS_ContentItems));
			OnCreated();
		}
		
		[Column(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_Username", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[Column(Storage="_DisplayName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_HashedEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HashedEmail
		{
			get
			{
				return this._HashedEmail;
			}
			set
			{
				if ((this._HashedEmail != value))
				{
					this.OnHashedEmailChanging(value);
					this.SendPropertyChanging();
					this._HashedEmail = value;
					this.SendPropertyChanged("HashedEmail");
					this.OnHashedEmailChanged();
				}
			}
		}
		
		[Column(Storage="_DefaultLanguageID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DefaultLanguageID
		{
			get
			{
				return this._DefaultLanguageID;
			}
			set
			{
				if ((this._DefaultLanguageID != value))
				{
					this.OnDefaultLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._DefaultLanguageID = value;
					this.SendPropertyChanged("DefaultLanguageID");
					this.OnDefaultLanguageIDChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="TinyInt NOT NULL")]
		public byte Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Association(Name="oxite_User_oxite_CMS_PageRoleUserRelationship", Storage="_oxite_CMS_PageRoleUserRelationships", ThisKey="UserID", OtherKey="UserID")]
		public EntitySet<oxite_CMS_PageRoleUserRelationship> oxite_CMS_PageRoleUserRelationships
		{
			get
			{
				return this._oxite_CMS_PageRoleUserRelationships;
			}
			set
			{
				this._oxite_CMS_PageRoleUserRelationships.Assign(value);
			}
		}
		
		[Association(Name="oxite_User_oxite_CMS_ContentItem", Storage="_oxite_CMS_ContentItems", ThisKey="UserID", OtherKey="CreatorUserID")]
		public EntitySet<oxite_CMS_ContentItem> oxite_CMS_ContentItems
		{
			get
			{
				return this._oxite_CMS_ContentItems;
			}
			set
			{
				this._oxite_CMS_ContentItems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_oxite_CMS_PageRoleUserRelationships(oxite_CMS_PageRoleUserRelationship entity)
		{
			this.SendPropertyChanging();
			entity.oxite_User = this;
		}
		
		private void detach_oxite_CMS_PageRoleUserRelationships(oxite_CMS_PageRoleUserRelationship entity)
		{
			this.SendPropertyChanging();
			entity.oxite_User = null;
		}
		
		private void attach_oxite_CMS_ContentItems(oxite_CMS_ContentItem entity)
		{
			this.SendPropertyChanging();
			entity.oxite_User = this;
		}
		
		private void detach_oxite_CMS_ContentItems(oxite_CMS_ContentItem entity)
		{
			this.SendPropertyChanging();
			entity.oxite_User = null;
		}
	}
	
	[Table(Name="dbo.oxite_CMS_ContentItem")]
	public partial class oxite_CMS_ContentItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SiteID;
		
		private System.Nullable<System.Guid> _PageID;
		
		private System.Guid _ContentItemID;
		
		private string _ContentItemName;
		
		private string _ContentItemDisplayName;
		
		private string _Body;
		
		private short _Version;
		
		private System.Guid _CreatorUserID;
		
		private System.DateTime _CreatedDate;
		
		private System.Nullable<System.DateTime> _PublishedDate;
		
		private EntityRef<oxite_CMS_Page> _oxite_CMS_Page;
		
		private EntityRef<oxite_User> _oxite_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSiteIDChanging(System.Guid value);
    partial void OnSiteIDChanged();
    partial void OnPageIDChanging(System.Nullable<System.Guid> value);
    partial void OnPageIDChanged();
    partial void OnContentItemIDChanging(System.Guid value);
    partial void OnContentItemIDChanged();
    partial void OnContentItemNameChanging(string value);
    partial void OnContentItemNameChanged();
    partial void OnContentItemDisplayNameChanging(string value);
    partial void OnContentItemDisplayNameChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnVersionChanging(short value);
    partial void OnVersionChanged();
    partial void OnCreatorUserIDChanging(System.Guid value);
    partial void OnCreatorUserIDChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnPublishedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishedDateChanged();
    #endregion
		
		public oxite_CMS_ContentItem()
		{
			this._oxite_CMS_Page = default(EntityRef<oxite_CMS_Page>);
			this._oxite_User = default(EntityRef<oxite_User>);
			OnCreated();
		}
		
		[Column(Storage="_SiteID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SiteID
		{
			get
			{
				return this._SiteID;
			}
			set
			{
				if ((this._SiteID != value))
				{
					this.OnSiteIDChanging(value);
					this.SendPropertyChanging();
					this._SiteID = value;
					this.SendPropertyChanged("SiteID");
					this.OnSiteIDChanged();
				}
			}
		}
		
		[Column(Storage="_PageID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> PageID
		{
			get
			{
				return this._PageID;
			}
			set
			{
				if ((this._PageID != value))
				{
					if (this._oxite_CMS_Page.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPageIDChanging(value);
					this.SendPropertyChanging();
					this._PageID = value;
					this.SendPropertyChanged("PageID");
					this.OnPageIDChanged();
				}
			}
		}
		
		[Column(Storage="_ContentItemID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ContentItemID
		{
			get
			{
				return this._ContentItemID;
			}
			set
			{
				if ((this._ContentItemID != value))
				{
					this.OnContentItemIDChanging(value);
					this.SendPropertyChanging();
					this._ContentItemID = value;
					this.SendPropertyChanged("ContentItemID");
					this.OnContentItemIDChanged();
				}
			}
		}
		
		[Column(Storage="_ContentItemName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContentItemName
		{
			get
			{
				return this._ContentItemName;
			}
			set
			{
				if ((this._ContentItemName != value))
				{
					this.OnContentItemNameChanging(value);
					this.SendPropertyChanging();
					this._ContentItemName = value;
					this.SendPropertyChanged("ContentItemName");
					this.OnContentItemNameChanged();
				}
			}
		}
		
		[Column(Storage="_ContentItemDisplayName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ContentItemDisplayName
		{
			get
			{
				return this._ContentItemDisplayName;
			}
			set
			{
				if ((this._ContentItemDisplayName != value))
				{
					this.OnContentItemDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._ContentItemDisplayName = value;
					this.SendPropertyChanged("ContentItemDisplayName");
					this.OnContentItemDisplayNameChanged();
				}
			}
		}
		
		[Column(Storage="_Body", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[Column(Storage="_Version", DbType="SmallInt NOT NULL")]
		public short Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[Column(Storage="_CreatorUserID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CreatorUserID
		{
			get
			{
				return this._CreatorUserID;
			}
			set
			{
				if ((this._CreatorUserID != value))
				{
					if (this._oxite_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreatorUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatorUserID = value;
					this.SendPropertyChanged("CreatorUserID");
					this.OnCreatorUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[Column(Storage="_PublishedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishedDate
		{
			get
			{
				return this._PublishedDate;
			}
			set
			{
				if ((this._PublishedDate != value))
				{
					this.OnPublishedDateChanging(value);
					this.SendPropertyChanging();
					this._PublishedDate = value;
					this.SendPropertyChanged("PublishedDate");
					this.OnPublishedDateChanged();
				}
			}
		}
		
		[Association(Name="oxite_CMS_Page_oxite_CMS_ContentItem", Storage="_oxite_CMS_Page", ThisKey="PageID", OtherKey="PageID", IsForeignKey=true)]
		public oxite_CMS_Page oxite_CMS_Page
		{
			get
			{
				return this._oxite_CMS_Page.Entity;
			}
			set
			{
				oxite_CMS_Page previousValue = this._oxite_CMS_Page.Entity;
				if (((previousValue != value) 
							|| (this._oxite_CMS_Page.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oxite_CMS_Page.Entity = null;
						previousValue.oxite_CMS_ContentItems.Remove(this);
					}
					this._oxite_CMS_Page.Entity = value;
					if ((value != null))
					{
						value.oxite_CMS_ContentItems.Add(this);
						this._PageID = value.PageID;
					}
					else
					{
						this._PageID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("oxite_CMS_Page");
				}
			}
		}
		
		[Association(Name="oxite_User_oxite_CMS_ContentItem", Storage="_oxite_User", ThisKey="CreatorUserID", OtherKey="UserID", IsForeignKey=true)]
		public oxite_User oxite_User
		{
			get
			{
				return this._oxite_User.Entity;
			}
			set
			{
				oxite_User previousValue = this._oxite_User.Entity;
				if (((previousValue != value) 
							|| (this._oxite_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._oxite_User.Entity = null;
						previousValue.oxite_CMS_ContentItems.Remove(this);
					}
					this._oxite_User.Entity = value;
					if ((value != null))
					{
						value.oxite_CMS_ContentItems.Add(this);
						this._CreatorUserID = value.UserID;
					}
					else
					{
						this._CreatorUserID = default(System.Guid);
					}
					this.SendPropertyChanged("oxite_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
